// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmd-GPGl7rGd-txXmogRJTIV6PJi2uRAM',
    appId: '1:778373166371:web:5538760a048d05f6580896',
    messagingSenderId: '778373166371',
    projectId: 'keygo-7d6d2',
    authDomain: 'keygo-7d6d2.firebaseapp.com',
    storageBucket: 'keygo-7d6d2.firebasestorage.app',
    measurementId: 'G-DVEB2EDP7M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9T-dAeNJ7F_GYpfu1UvCHQDDCeFfqPtQ',
    appId: '1:778373166371:android:a8bb7f60bc7b0e12580896',
    messagingSenderId: '778373166371',
    projectId: 'keygo-7d6d2',
    storageBucket: 'keygo-7d6d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGLkt9eamxEXiAfs0oAaEBjSO_WlB5Nko',
    appId: '1:778373166371:ios:6f98b517dc916e22580896',
    messagingSenderId: '778373166371',
    projectId: 'keygo-7d6d2',
    storageBucket: 'keygo-7d6d2.firebasestorage.app',
    iosBundleId: 'com.example.keygoDeneme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGLkt9eamxEXiAfs0oAaEBjSO_WlB5Nko',
    appId: '1:778373166371:ios:6f98b517dc916e22580896',
    messagingSenderId: '778373166371',
    projectId: 'keygo-7d6d2',
    storageBucket: 'keygo-7d6d2.firebasestorage.app',
    iosBundleId: 'com.example.keygoDeneme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmd-GPGl7rGd-txXmogRJTIV6PJi2uRAM',
    appId: '1:778373166371:web:e61f29a95ccffc91580896',
    messagingSenderId: '778373166371',
    projectId: 'keygo-7d6d2',
    authDomain: 'keygo-7d6d2.firebaseapp.com',
    storageBucket: 'keygo-7d6d2.firebasestorage.app',
    measurementId: 'G-XCJMSC7S5M',
  );
}
